### ISSUE TITLE
mPermissionsRequester.request(); causes an exception

### ISSUE THREAD

**Issue by lectricas** [beworker/rx-android-permissions#3]
Hi. I was following your example and executing 
`mPermissionsRequester.request();`
on a button click.
But all I have is ake sure you request permissions by calling RxPermissions.request(...) method first.
Then I did this:

`mPermissionsRequester.performRequestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION});`

And I also got the same exception in 

```
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        mPermissionsRequester.onRequestPermissionsResult(permissions, grantResults);
    }
```

this line.
Can you help me?

**Comment by sergejsha** [comment]
What is the exception exactly?

**Comment by lectricas** [comment]
@beworker 

```
Process: com.example.xals.fixedrec4_1, PID: 3794
                                                                            java.lang.IllegalStateException: Make sure you request permissions by calling RxPermissions.request(...) method first.
                                                                                at com.example.xals.fixedrec4_1.util.RxPermissions.assertInitialized(RxPermissions.java:182)
                                                                                at com.example.xals.fixedrec4_1.util.RxPermissions.access$000(RxPermissions.java:22)
                                                                                at com.example.xals.fixedrec4_1.util.RxPermissions$PermissionsRequester.request(RxPermissions.java:71)
                                                                                at com.example.xals.fixedrec4_1.mvp.trackslist.TracksFragment.requestPermissionReactive(TracksFragment.java:98)
                                                                                at com.example.xals.fixedrec4_1.mvp.trackslist.TracksFragment.onClick(TracksFragment.java:72)
                                                                                at com.example.xals.fixedrec4_1.mvp.trackslist.TracksFragment$$ViewBinder$1.doClick(TracksFragment$$ViewBinder.java:20)
                                                                                at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                at android.view.View.performClick(View.java:5204)
                                                                                at android.view.View$PerformClick.run(View.java:21153)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
This is the code i run.

    private final RxPermissions.PermissionsRequester mPermissionsRequester = new RxPermissions.PermissionsRequester() {
        @Override public void performRequestPermissions(String[] permissions) {
            // forward request to the system by calling fragment's method
            requestPermissions(permissions, REQ_PERMISSIONS);
        }
    };

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        if (requestCode == REQ_PERMISSIONS) {
            // forward response back to requester class for further processing
            mPermissionsRequester.onRequestPermissionsResult(permissions, grantResults);
        }
    }

    private void requestPermissionReactive() {

        mPermissionsRequester.request(); // also tried mPermissionsRequester.request(new String{SOMEPERMISSION})

}

**Comment by sergejsha** [comment]
You need to initialize `RxPermissions` and subscribe for the events as it is shown in the `onViewCreated()` method. Otherwise no observer will the created and the assertion you receive will be thrown.

**Comment by lectricas** [comment]
Ok, now I see that I can ask a user to grant a permission by:
```
mSubscription = RxPermissions.get(getActivity())
            .request(mPermissionsRequester, 
```
but why it is in onViewCreate, not in button click?
What is the purpose of:

`mPermissionsRequester.request();`

**Comment by sergejsha** [comment]
Because for the very first time the app should ask for permissions immediately, without bothering the user. If permissions are already given, then your subscription will be executed immediately and you can do things you want. If some permissions are not given, there will be a permissions dialog shown to the user. Now, if user denies giving the permissions, and you want to show that dialog once again, *only then* you should use `request()` method mentioned. Thus, it is just a mean to show a dialog once again, if user denied the permissions previously.

**Comment by lectricas** [comment]
thank you, now I get it.

**Comment by sergejsha** [comment]
You are welcome!
